<template>
  <div class="">
    <table :data="jsonDataArr"></table>
  </div>
</template>

<script>
export default {
  components: {},
  setup() {
    const jsonDataArr = [
      {
        contingent_liabilities: {
          contingent_liability: [
            {
              amount: "",
              subject_type: "",
              overdue_debt_sum: "",
              org: "",
              contract_id: "",
              overdue_debt_sum_change: "",
              contract_status: "",
              branch: "",
              amount_change: "",
              percent: "",
              contract_end_date: "",
              max_current_overdue: "",
              contract_date: "",
              total_debt_sum: "",
              currency: "",
              total_debt_sum_change: "",
              percent_change: "",
            },
          ],
        },
        overview: {
          contingent_liabilities_qty: 0,
          max_overdue_principal_sum: 0.0,
          max_uninter_overdue_percent_days: 0,
          max_overdue_principal_days: 0,
          total_overdue_percent_sum: 0.0,
          credit_request_qty: 96,
          claims_qty: 27,
          average_monthly_payment: 132046569.0,
          subscriptions_qty: 0,
          contracts_qty: 3,
          overdue_principal_qty: 0,
        },
        subscriptions: {
          subscription: [
            {
              org: "",
              user_id: "",
              claim_id: "",
              subscription_period: "",
              consent_date: "",
              branch: "",
              consent_id: "",
            },
          ],
        },
        scorring: {
          scoring_version: "1.2",
          scoring_grade: "327",
          scoring_class: "B1",
          scoring_level: "ХОРОШИЙ",
        },
        sysinfo: {
          demand_id: "RET2022111967643",
          notes:
            "1.\tПредоставление и использование кредитной информации регулируется законом № ЗРУ-301 «Об обмене кредитной информацией» от 04.10.2011 г.\n2.\tКредитное бюро не проставляет запрета на кредитование, не вносит субъекта кредитной информации в «чёрный» список и не осуществляет никаких корректировок, исправлений, удалений в кредитную информацию, отражённой в кредитном отчёте. Внести изменения вправе, организация, предоставившая информацию, и только в случае, если данные переданы неверно или ошибочно.\n3.\tЕсли субъект кредитной информации не согласен с какой-либо информацией, содержащейся в кредитном отчёте, субъекту кредитной информации необходимо обратиться сперва к поставщику информации, а затем в кредитное бюро с заявлением об оспаривании информации.\n4.\tСкоринговый балл имеет рекомендательный характер и может быть основанием для выдачи или отказа кредитов только по усмотрению кредитора.\n5.\tНегативные факторы во время льготного периода в период пандемии с 01.03.2020-01.10.2020 не влияют на скоринговый балл.\n6.\tСреднемесячный платёж включает в себя расчёт исходя из остатков основного долга и прогнозного платежа по процентам (аннуитетный).\n7.\tКредиты в иностранной валюте в совокупных суммах рассчитывается в сумовом эквиваленте по курсу ЦБ РУз на дату формирования кредитного отчёта.\n8.\tПри изменениях расчётов меняется версия скорингового балла.",
          org: "RET",
          user_id: "TAQSIM SARMOYA (20176), System S.S",
          claim_id: "358",
          report_type: "077",
          consent_date: "2022- 04-21",
          report_name: "InfoScore (XML)",
          demand_date_time: "2022-04-21 11:27",
          branch: "20176",
          consent_id: "384",
          claim_date: "2022- 04-21",
        },
        credit_requests: {
          credit_request: [
            {
              org: "RET",
              user_id: "System S.S.",
              claim_id: "358",
              report_type: "025",
              consent_date: "2022-04-21",
              demand_date_time: "2022-04-21 11:27",
              branch: "20176",
              consent_id: "384",
            },
            {
              org: "RET",
              user_id: "System S.S.",
              claim_id: "358",
              report_type: "039",
              consent_date: "2022-04-21",
              demand_date_time: "2022-04-21 11:27",
              branch: "20176",
              consent_id: "384",
            },
            {
              org: "RET",
              user_id: "System S.S.",
              claim_id: "358",
              report_type: "070",
              consent_date: "2022-04-21",
              demand_date_time: "2022-04-21 11:27",
              branch: "20176",
              consent_id: "384",
            },
            {
              org: "RET",
              user_id: "System S.S.",
              claim_id: "358",
              report_type: "077",
              consent_date: "2022-04-21",
              demand_date_time: "2022-04-21 11:27",
              branch: "20176",
              consent_id: "384",
            },
            {
              org: "RET",
              user_id: "System S.S.",
              claim_id: "348",
              report_type: "025",
              consent_date: "2022-04-19",
              demand_date_time: "2022-04-19 15:35",
              branch: "20176",
              consent_id: "380",
            },
            {
              org: "RET",
              user_id: "System S.S.",
              claim_id: "348",
              report_type: "039",
              consent_date: "2022-04-19",
              demand_date_time: "2022-04-19 15:35",
              branch: "20176",
              consent_id: "380",
            },
            {
              org: "RET",
              user_id: "System S.S.",
              claim_id: "348",
              report_type: "070",
              consent_date: "2022-04-19",
              demand_date_time: "2022-04-19 15:35",
              branch: "20176",
              consent_id: "380",
            },
            {
              org: "RET",
              user_id: "System S.S.",
              claim_id: "348",
              report_type: "077",
              consent_date: "2022-04-19",
              demand_date_time: "2022-04-19 15:35",
              branch: "20176",
              consent_id: "380",
            },
            {
              org: "RET",
              user_id: "System S.S.",
              claim_id: "317",
              report_type: "025",
              consent_date: "2022-04-14",
              demand_date_time: "2022-04-14 11:05",
              branch: "20176",
              consent_id: "341",
            },
            {
              org: "RET",
              user_id: "System S.S.",
              claim_id: "317",
              report_type: "025",
              consent_date: "2022-04-14",
              demand_date_time: "2022-04-14 22:41",
              branch: "20176",
              consent_id: "341",
            },
            {
              org: "RET",
              user_id: "System S.S.",
              claim_id: "317",
              report_type: "039",
              consent_date: "2022-04-14",
              demand_date_time: "2022-04-14 11:05",
              branch: "20176",
              consent_id: "341",
            },
            {
              org: "RET",
              user_id: "System S.S.",
              claim_id: "317",
              report_type: "039",
              consent_date: "2022-04-14",
              demand_date_time: "2022-04-14 22:41",
              branch: "20176",
              consent_id: "341",
            },
            {
              org: "RET",
              user_id: "System S.S.",
              claim_id: "317",
              report_type: "070",
              consent_date: "2022-04-14",
              demand_date_time: "2022-04-14 11:05",
              branch: "20176",
              consent_id: "341",
            },
            {
              org: "RET",
              user_id: "System S.S.",
              claim_id: "317",
              report_type: "070",
              consent_date: "2022-04-14",
              demand_date_time: "2022-04-14 22:41",
              branch: "20176",
              consent_id: "341",
            },
            {
              org: "RET",
              user_id: "System S.S.",
              claim_id: "317",
              report_type: "077",
              consent_date: "2022-04-14",
              demand_date_time: "2022-04-14 11:05",
              branch: "20176",
              consent_id: "341",
            },
            {
              org: "RET",
              user_id: "System S.S.",
              claim_id: "317",
              report_type: "077",
              consent_date: "2022-04-14",
              demand_date_time: "2022-04-14 22:41",
              branch: "20176",
              consent_id: "341",
            },
            {
              org: "RET",
              user_id: "System S.S.",
              claim_id: "300",
              report_type: "023",
              consent_date: "2022-04-07",
              demand_date_time: "2022-04-11 09:34",
              branch: "20176",
              consent_id: "331",
            },
            {
              org: "RET",
              user_id: "System S.S.",
              claim_id: "300",
              report_type: "025",
              consent_date: "2022-04-07",
              demand_date_time: "2022-04-07 10:47",
              branch: "20176",
              consent_id: "331",
            },
            {
              org: "RET",
              user_id: "System S.S.",
              claim_id: "300",
              report_type: "039",
              consent_date: "2022-04-07",
              demand_date_time: "2022-04-07 10:47",
              branch: "20176",
              consent_id: "331",
            },
            {
              org: "RET",
              user_id: "System S.S.",
              claim_id: "300",
              report_type: "070",
              consent_date: "2022-04-07",
              demand_date_time: "2022-04-07 10:47",
              branch: "20176",
              consent_id: "331",
            },
            {
              org: "RET",
              user_id: "System S.S.",
              claim_id: "300",
              report_type: "077",
              consent_date: "2022-04-07",
              demand_date_time: "2022-04-07 10:48",
              branch: "20176",
              consent_id: "331",
            },
            {
              org: "RET",
              user_id: "System S.S.",
              claim_id: "298",
              report_type: "025",
              consent_date: "2022-04-07",
              demand_date_time: "2022-04-07 10:17",
              branch: "20176",
              consent_id: "330",
            },
            {
              org: "RET",
              user_id: "System S.S.",
              claim_id: "298",
              report_type: "039",
              consent_date: "2022-04-07",
              demand_date_time: "2022-04-07 10:17",
              branch: "20176",
              consent_id: "330",
            },
            {
              org: "RET",
              user_id: "System S.S.",
              claim_id: "298",
              report_type: "070",
              consent_date: "2022-04-07",
              demand_date_time: "2022-04-07 10:17",
              branch: "20176",
              consent_id: "330",
            },
            {
              org: "RET",
              user_id: "System S.S.",
              claim_id: "298",
              report_type: "077",
              consent_date: "2022-04-07",
              demand_date_time: "2022-04-07 10:17",
              branch: "20176",
              consent_id: "330",
            },
            {
              org: "014",
              user_id: "System S.S.",
              claim_id: "F00303589",
              report_type: "008",
              consent_date: "2022-04-07",
              demand_date_time: "2022-04-07 21:16",
              branch: "01145",
              consent_id: "F00303589",
            },
            {
              org: "RET",
              user_id: "System S.S.",
              claim_id: "295",
              report_type: "025",
              consent_date: "2022-04-06",
              demand_date_time: "2022-04-06 16:16",
              branch: "20176",
              consent_id: "328",
            },
            {
              org: "RET",
              user_id: "System S.S.",
              claim_id: "295",
              report_type: "025",
              consent_date: "2022-04-06",
              demand_date_time: "2022-04-06 17:00",
              branch: "20176",
              consent_id: "328",
            },
            {
              org: "RET",
              user_id: "System S.S.",
              claim_id: "295",
              report_type: "039",
              consent_date: "2022-04-06",
              demand_date_time: "2022-04-06 16:16",
              branch: "20176",
              consent_id: "328",
            },
            {
              org: "RET",
              user_id: "System S.S.",
              claim_id: "295",
              report_type: "039",
              consent_date: "2022-04-06",
              demand_date_time: "2022-04-06 17:00",
              branch: "20176",
              consent_id: "328",
            },
            {
              org: "RET",
              user_id: "System S.S.",
              claim_id: "295",
              report_type: "070",
              consent_date: "2022-04-06",
              demand_date_time: "2022-04-06 16:16",
              branch: "20176",
              consent_id: "328",
            },
            {
              org: "RET",
              user_id: "System S.S.",
              claim_id: "295",
              report_type: "070",
              consent_date: "2022-04-06",
              demand_date_time: "2022-04-06 17:00",
              branch: "20176",
              consent_id: "328",
            },
            {
              org: "RET",
              user_id: "System S.S.",
              claim_id: "295",
              report_type: "077",
              consent_date: "2022-04-06",
              demand_date_time: "2022-04-06 16:17",
              branch: "20176",
              consent_id: "328",
            },
            {
              org: "RET",
              user_id: "System S.S.",
              claim_id: "295",
              report_type: "077",
              consent_date: "2022-04-06",
              demand_date_time: "2022-04-06 17:00",
              branch: "20176",
              consent_id: "328",
            },
            {
              org: "RET",
              user_id: "System S.S.",
              claim_id: "292",
              report_type: "025",
              consent_date: "2022-04-05",
              demand_date_time: "2022-04-05 12:38",
              branch: "20176",
              consent_id: "324",
            },
            {
              org: "RET",
              user_id: "System S.S.",
              claim_id: "292",
              report_type: "039",
              consent_date: "2022-04-05",
              demand_date_time: "2022-04-05 12:38",
              branch: "20176",
              consent_id: "324",
            },
            {
              org: "RET",
              user_id: "System S.S.",
              claim_id: "292",
              report_type: "070",
              consent_date: "2022-04-05",
              demand_date_time: "2022-04-05 12:38",
              branch: "20176",
              consent_id: "324",
            },
            {
              org: "RET",
              user_id: "System S.S.",
              claim_id: "292",
              report_type: "077",
              consent_date: "2022-04-05",
              demand_date_time: "2022-04-05 12:39",
              branch: "20176",
              consent_id: "324",
            },
            {
              org: "RET",
              user_id: "System S.S.",
              claim_id: "285",
              report_type: "025",
              consent_date: "2022-03-30",
              demand_date_time: "2022-03-30 17:18",
              branch: "20176",
              consent_id: "312",
            },
            {
              org: "RET",
              user_id: "System S.S.",
              claim_id: "285",
              report_type: "025",
              consent_date: "2022-03-30",
              demand_date_time: "2022-04-04 11:57",
              branch: "20176",
              consent_id: "312",
            },
            {
              org: "RET",
              user_id: "System S.S.",
              claim_id: "285",
              report_type: "039",
              consent_date: "2022-03-30",
              demand_date_time: "2022-03-30 17:18",
              branch: "20176",
              consent_id: "312",
            },
            {
              org: "RET",
              user_id: "System S.S.",
              claim_id: "285",
              report_type: "039",
              consent_date: "2022-03-30",
              demand_date_time: "2022-04-04 11:57",
              branch: "20176",
              consent_id: "312",
            },
            {
              org: "RET",
              user_id: "System S.S.",
              claim_id: "285",
              report_type: "070",
              consent_date: "2022-03-30",
              demand_date_time: "2022-03-30 17:18",
              branch: "20176",
              consent_id: "312",
            },
            {
              org: "RET",
              user_id: "System S.S.",
              claim_id: "285",
              report_type: "070",
              consent_date: "2022-03-30",
              demand_date_time: "2022-04-04 11:57",
              branch: "20176",
              consent_id: "312",
            },
            {
              org: "RET",
              user_id: "System S.S.",
              claim_id: "285",
              report_type: "077",
              consent_date: "2022-03-30",
              demand_date_time: "2022-03-30 17:19",
              branch: "20176",
              consent_id: "312",
            },
            {
              org: "RET",
              user_id: "System S.S.",
              claim_id: "285",
              report_type: "077",
              consent_date: "2022-03-30",
              demand_date_time: "2022-04-04 11:57",
              branch: "20176",
              consent_id: "312",
            },
            {
              org: "RET",
              user_id: "System S.S.",
              claim_id: "210",
              report_type: "025",
              consent_date: "2022-03-30",
              demand_date_time: "2022-03-30 14:56",
              branch: "20176",
              consent_id: "309",
            },
            {
              org: "RET",
              user_id: "System S.S.",
              claim_id: "210",
              report_type: "025",
              consent_date: "2022-03-30",
              demand_date_time: "2022-03-30 16:29",
              branch: "20176",
              consent_id: "309",
            },
            {
              org: "RET",
              user_id: "System S.S.",
              claim_id: "210",
              report_type: "039",
              consent_date: "2022-03-30",
              demand_date_time: "2022-03-30 14:55",
              branch: "20176",
              consent_id: "309",
            },
            {
              org: "RET",
              user_id: "System S.S.",
              claim_id: "210",
              report_type: "039",
              consent_date: "2022-03-30",
              demand_date_time: "2022-03-30 16:29",
              branch: "20176",
              consent_id: "309",
            },
            {
              org: "RET",
              user_id: "System S.S.",
              claim_id: "210",
              report_type: "070",
              consent_date: "2022-03-30",
              demand_date_time: "2022-03-30 14:55",
              branch: "20176",
              consent_id: "309",
            },
            {
              org: "RET",
              user_id: "System S.S.",
              claim_id: "210",
              report_type: "070",
              consent_date: "2022-03-30",
              demand_date_time: "2022-03-30 16:29",
              branch: "20176",
              consent_id: "309",
            },
            {
              org: "RET",
              user_id: "System S.S.",
              claim_id: "210",
              report_type: "077",
              consent_date: "2022-03-30",
              demand_date_time: "2022-03-30 14:56",
              branch: "20176",
              consent_id: "309",
            },
            {
              org: "RET",
              user_id: "System S.S.",
              claim_id: "210",
              report_type: "077",
              consent_date: "2022-03-30",
              demand_date_time: "2022-03-30 16:29",
              branch: "20176",
              consent_id: "309",
            },
            {
              org: "RET",
              user_id: "System S.S.",
              claim_id: "124",
              report_type: "025",
              consent_date: "2022-02-17",
              demand_date_time: "2022-02-17 14:08",
              branch: "20176",
              consent_id: "0",
            },
            {
              org: "RET",
              user_id: "System S.S.",
              claim_id: "124",
              report_type: "025",
              consent_date: "2022-02-17",
              demand_date_time: "2022-02-18 16:07",
              branch: "20176",
              consent_id: "0",
            },
            {
              org: "RET",
              user_id: "System S.S.",
              claim_id: "124",
              report_type: "025",
              consent_date: "2022-02-17",
              demand_date_time: "2022-02-18 17:21",
              branch: "20176",
              consent_id: "0",
            },
            {
              org: "RET",
              user_id: "System S.S.",
              claim_id: "124",
              report_type: "025",
              consent_date: "2022-02-17",
              demand_date_time: "2022-02-18 18:36",
              branch: "20176",
              consent_id: "0",
            },
            {
              org: "RET",
              user_id: "System S.S.",
              claim_id: "124",
              report_type: "025",
              consent_date: "2022-02-17",
              demand_date_time: "2022-02-18 20:29",
              branch: "20176",
              consent_id: "0",
            },
            {
              org: "RET",
              user_id: "System S.S.",
              claim_id: "124",
              report_type: "039",
              consent_date: "2022-02-17",
              demand_date_time: "2022-02-17 14:07",
              branch: "20176",
              consent_id: "0",
            },
            {
              org: "RET",
              user_id: "System S.S.",
              claim_id: "124",
              report_type: "039",
              consent_date: "2022-02-17",
              demand_date_time: "2022-02-18 16:07",
              branch: "20176",
              consent_id: "0",
            },
            {
              org: "RET",
              user_id: "System S.S.",
              claim_id: "124",
              report_type: "039",
              consent_date: "2022-02-17",
              demand_date_time: "2022-02-18 17:20",
              branch: "20176",
              consent_id: "0",
            },
            {
              org: "RET",
              user_id: "System S.S.",
              claim_id: "124",
              report_type: "039",
              consent_date: "2022-02-17",
              demand_date_time: "2022-02-18 18:36",
              branch: "20176",
              consent_id: "0",
            },
            {
              org: "RET",
              user_id: "System S.S.",
              claim_id: "124",
              report_type: "039",
              consent_date: "2022-02-17",
              demand_date_time: "2022-02-18 20:29",
              branch: "20176",
              consent_id: "0",
            },
            {
              org: "RET",
              user_id: "System S.S.",
              claim_id: "124",
              report_type: "070",
              consent_date: "2022-02-17",
              demand_date_time: "2022-02-17 14:08",
              branch: "20176",
              consent_id: "0",
            },
            {
              org: "RET",
              user_id: "System S.S.",
              claim_id: "124",
              report_type: "070",
              consent_date: "2022-02-17",
              demand_date_time: "2022-02-18 16:07",
              branch: "20176",
              consent_id: "0",
            },
            {
              org: "RET",
              user_id: "System S.S.",
              claim_id: "124",
              report_type: "070",
              consent_date: "2022-02-17",
              demand_date_time: "2022-02-18 17:20",
              branch: "20176",
              consent_id: "0",
            },
            {
              org: "RET",
              user_id: "System S.S.",
              claim_id: "124",
              report_type: "070",
              consent_date: "2022-02-17",
              demand_date_time: "2022-02-18 18:36",
              branch: "20176",
              consent_id: "0",
            },
            {
              org: "RET",
              user_id: "System S.S.",
              claim_id: "124",
              report_type: "070",
              consent_date: "2022-02-17",
              demand_date_time: "2022-02-18 20:29",
              branch: "20176",
              consent_id: "0",
            },
            {
              org: "RET",
              user_id: "System S.S.",
              claim_id: "124",
              report_type: "077",
              consent_date: "2022-02-17",
              demand_date_time: "2022-02-17 14:08",
              branch: "20176",
              consent_id: "0",
            },
            {
              org: "RET",
              user_id: "System S.S.",
              claim_id: "124",
              report_type: "077",
              consent_date: "2022-02-17",
              demand_date_time: "2022-02-18 16:07",
              branch: "20176",
              consent_id: "0",
            },
            {
              org: "RET",
              user_id: "System S.S.",
              claim_id: "124",
              report_type: "077",
              consent_date: "2022-02-17",
              demand_date_time: "2022-02-18 17:21",
              branch: "20176",
              consent_id: "0",
            },
            {
              org: "RET",
              user_id: "System S.S.",
              claim_id: "124",
              report_type: "077",
              consent_date: "2022-02-17",
              demand_date_time: "2022-02-18 18:37",
              branch: "20176",
              consent_id: "0",
            },
            {
              org: "RET",
              user_id: "System S.S.",
              claim_id: "124",
              report_type: "077",
              consent_date: "2022-02-17",
              demand_date_time: "2022-02-18 20:29",
              branch: "20176",
              consent_id: "0",
            },
            {
              org: "014",
              user_id: "System S.S.",
              claim_id: "F00265430",
              report_type: "008",
              consent_date: "2022-02-17",
              demand_date_time: "2022-02-17 21:31",
              branch: "01145",
              consent_id: "F00265430",
            },
            {
              org: "014",
              user_id: "System S.S.",
              claim_id: "F00265430",
              report_type: "008",
              consent_date: "2022-02-17",
              demand_date_time: "2022-03-11 15:43",
              branch: "01145",
              consent_id: "F00265430",
            },
            {
              org: "014",
              user_id: "(система)",
              claim_id: "36533",
              report_type: "001",
              consent_date: "2022-01-17",
              demand_date_time: "2022-03-09 18:35",
              branch: "01145",
              consent_id: "36533",
            },
            {
              org: "014",
              user_id: "System S.S.",
              claim_id: "F00241967",
              report_type: "008",
              consent_date: "2022-01-16",
              demand_date_time: "2022-01-16 20:47",
              branch: "01145",
              consent_id: "F00241967",
            },
            {
              org: "RET",
              user_id: "System S.S.",
              claim_id: "36811",
              report_type: "008",
              consent_date: "2021-11-01",
              demand_date_time: "2021-11-01 18:00",
              branch: "20002",
              consent_id: "0000036811",
            },
            {
              org: "RET",
              user_id: "System S.S.",
              claim_id: "36811",
              report_type: "039",
              consent_date: "2021-11-01",
              demand_date_time: "2021-11-01 18:01",
              branch: "20002",
              consent_id: "0000036811",
            },
            {
              org: "014",
              user_id: "System S.S.",
              claim_id: "F00192603",
              report_type: "008",
              consent_date: "2021-11-01",
              demand_date_time: "2021-11-01 17:19",
              branch: "00444",
              consent_id: "F00192603",
            },
            {
              org: "014",
              user_id: "System S.S.",
              claim_id: "F00192603",
              report_type: "008",
              consent_date: "2021-11-01",
              demand_date_time: "2021-11-01 18:05",
              branch: "00444",
              consent_id: "F00192603",
            },
            {
              org: "014",
              user_id: "System S.S.",
              claim_id: "F00192603",
              report_type: "008",
              consent_date: "2021-11-01",
              demand_date_time: "2021-11-02 00:01",
              branch: "00444",
              consent_id: "F00192603",
            },
            {
              org: "RET",
              user_id: "System S.S.",
              claim_id: "2f5b728472",
              report_type: "023",
              consent_date: "2021-10-29",
              demand_date_time: "2021-10-29 15:34",
              branch: "20100",
              consent_id: "2f5b728472",
            },
            {
              org: "RET",
              user_id: "System S.S.",
              claim_id: "177abd312a",
              report_type: "023",
              consent_date: "2021-10-29",
              demand_date_time: "2021-10-29 15:34",
              branch: "20100",
              consent_id: "177abd312a",
            },
            {
              org: "RET",
              user_id: "System S.S.",
              claim_id: "ac346309a398277",
              report_type: "007",
              consent_date: "2021-10-29",
              demand_date_time: "2021-10-29 15:13",
              branch: "20038",
              consent_id: "398277",
            },
            {
              org: "RET",
              user_id: "System S.S.",
              claim_id: "ac346309a398277",
              report_type: "022",
              consent_date: "2021-10-29",
              demand_date_time: "2021-10-29 15:13",
              branch: "20038",
              consent_id: "398277",
            },
            {
              org: "RET",
              user_id: "System S.S.",
              claim_id: "ac346309a398277",
              report_type: "022",
              consent_date: "2021-10-29",
              demand_date_time: "2021-11-01 17:30",
              branch: "20038",
              consent_id: "398277",
            },
            {
              org: "RET",
              user_id: "System S.S.",
              claim_id: "ac346309a398277",
              report_type: "023",
              consent_date: "2021-10-29",
              demand_date_time: "2021-10-29 15:13",
              branch: "20038",
              consent_id: "398277",
            },
            {
              org: "RET",
              user_id: "System S.S.",
              claim_id: "ac346309a398277",
              report_type: "025",
              consent_date: "2021-10-29",
              demand_date_time: "2021-10-29 15:13",
              branch: "20038",
              consent_id: "398277",
            },
            {
              org: "RET",
              user_id: "System S.S.",
              claim_id: "ac346309a398277",
              report_type: "039",
              consent_date: "2021-10-29",
              demand_date_time: "2021-10-29 15:13",
              branch: "20038",
              consent_id: "398277",
            },
            {
              org: "RET",
              user_id: "System S.S.",
              claim_id: "ac346309a398277",
              report_type: "039",
              consent_date: "2021-10-29",
              demand_date_time: "2021-11-01 17:30",
              branch: "20038",
              consent_id: "398277",
            },
            {
              org: "RET",
              user_id: "System S.S.",
              claim_id: "ac346309a398277",
              report_type: "155",
              consent_date: "2021-10-29",
              demand_date_time: "2021-10-29 15:13",
              branch: "20038",
              consent_id: "398277",
            },
            {
              org: "RET",
              user_id: "System S.S.",
              claim_id: "ac346309a398277",
              report_type: "177",
              consent_date: "2021-10-29",
              demand_date_time: "2021-10-29 15:13",
              branch: "20038",
              consent_id: "398277",
            },
            {
              org: "009",
              user_id: "System S.S.",
              claim_id: "796929",
              report_type: "022",
              consent_date: "2021-10-29",
              demand_date_time: "2021-10-29 15:01",
              branch: "01037",
              consent_id: "1",
            },
            {
              org: "048",
              user_id: "(система)",
              claim_id: "202664",
              report_type: "003",
              consent_date: "2020-01-22",
              demand_date_time: "2020-01-22 11:29",
              branch: "00996",
              consent_id: "5554",
            },
          ],
        },
        client: {
          pinfl: "33103940270022",
          live_address: "",
          registration_region: "0",
          gender: "M",
          registration_district: "0",
          birth_date: "1994-03-31",
          inn: "508150640",
          client_type: "08",
          founders: "Информация временно не доступна",
          oked: "",
          email_change: "2022-04-21",
          juridical_status: "2",
          name: "SULTANBAYEV SHERZOD SARVAR O‘G‘LI",
          live_address_change: "2022-04-21",
          registration_address: "Mirzo skdkdk djdj",
          email: "н/д",
          registration_address_change: "2022-04-21",
        },
        blacklist: {
          blacklist_info: [
            {
              claim_id: "",
              exclusion_date: "",
              org_name: "",
              inclusion_date: "",
              claim_date: "",
            },
            {
              claim_id: "",
              exclusion_date: "",
              org_name: "",
              inclusion_date: "",
              claim_date: "",
            },
          ],
        },
        open_contracts: {
          open_contract: [
            {
              monthly_average_payment: "124180558",
              overdue_debt_sum: "0",
              org: "014",
              contract_id: "MZ_ONLINE 271717",
              total_debt_sum: "973815105",
              currency: "000",
              branch: "01145",
            },
            {
              monthly_average_payment: "7866011",
              overdue_debt_sum: "0",
              org: "048",
              contract_id: "297606",
              total_debt_sum: "149454213",
              currency: "000",
              branch: "01186",
            },
          ],
        },
        claims_wo_contracts: {
          claim_wo_contract: [
            {
              rejection_date: "2021-11-30",
              summa: "",
              org: "009",
              claim_id: "796929",
              rejection_reason: "12",
              currency: "н\\д",
              branch: "01037",
              claim_date: "2021-10-29",
            },
            {
              rejection_date: "2021-12-02",
              summa: "",
              org: "014",
              claim_id: "F00192603",
              rejection_reason: "08",
              currency: "н\\д",
              branch: "00444",
              claim_date: "2021-11-01",
            },
            {
              rejection_date: "2022-02-16",
              summa: "",
              org: "014",
              claim_id: "F00241967",
              rejection_reason: "08",
              currency: "н\\д",
              branch: "01145",
              claim_date: "2022-01-16",
            },
            {
              rejection_date: "2022-03-20",
              summa: "",
              org: "014",
              claim_id: "F00265430",
              rejection_reason: "08",
              currency: "н\\д",
              branch: "01145",
              claim_date: "2022-02-17",
            },
            {
              rejection_date: "",
              summa: "",
              org: "014",
              claim_id: "F00303589",
              rejection_reason: "",
              currency: "н\\д",
              branch: "01145",
              claim_date: "2022-04-07",
            },
            {
              rejection_date: "2021-11-01",
              summa: "",
              org: "RET",
              claim_id: "36811",
              rejection_reason: "",
              currency: "н\\д",
              branch: "20002",
              claim_date: "2021-11-01",
            },
            {
              rejection_date: "2021-11-30",
              summa: "",
              org: "RET",
              claim_id: "ac346309a398277",
              rejection_reason: "",
              currency: "н\\д",
              branch: "20038",
              claim_date: "2021-10-29",
            },
            {
              rejection_date: "",
              summa: "",
              org: "RET",
              claim_id: "177abd312a",
              rejection_reason: "",
              currency: "н\\д",
              branch: "20100",
              claim_date: "2021-10-29",
            },
            {
              rejection_date: "",
              summa: "",
              org: "RET",
              claim_id: "2f5b728472",
              rejection_reason: "",
              currency: "н\\д",
              branch: "20100",
              claim_date: "2021-10-29",
            },
            {
              rejection_date: "",
              summa: "",
              org: "RET",
              claim_id: "10098240722",
              rejection_reason: "",
              currency: "н\\д",
              branch: "20176",
              claim_date: "2021-11-19",
            },
            {
              rejection_date: "",
              summa: "",
              org: "RET",
              claim_id: "10098240723",
              rejection_reason: "",
              currency: "н\\д",
              branch: "20176",
              claim_date: "2021-11-19",
            },
            {
              rejection_date: "",
              summa: "",
              org: "RET",
              claim_id: "10098240730",
              rejection_reason: "",
              currency: "н\\д",
              branch: "20176",
              claim_date: "2021-11-19",
            },
            {
              rejection_date: "",
              summa: "",
              org: "RET",
              claim_id: "124",
              rejection_reason: "",
              currency: "н\\д",
              branch: "20176",
              claim_date: "2022-02-17",
            },
            {
              rejection_date: "",
              summa: "",
              org: "RET",
              claim_id: "210",
              rejection_reason: "",
              currency: "н\\д",
              branch: "20176",
              claim_date: "2022-03-30",
            },
            {
              rejection_date: "",
              summa: "",
              org: "RET",
              claim_id: "285",
              rejection_reason: "",
              currency: "н\\д",
              branch: "20176",
              claim_date: "2022-03-30",
            },
            {
              rejection_date: "",
              summa: "",
              org: "RET",
              claim_id: "292",
              rejection_reason: "",
              currency: "н\\д",
              branch: "20176",
              claim_date: "2022-04-05",
            },
            {
              rejection_date: "",
              summa: "",
              org: "RET",
              claim_id: "295",
              rejection_reason: "",
              currency: "н\\д",
              branch: "20176",
              claim_date: "2022-04-06",
            },
            {
              rejection_date: "",
              summa: "",
              org: "RET",
              claim_id: "298",
              rejection_reason: "",
              currency: "н\\д",
              branch: "20176",
              claim_date: "2022-04-07",
            },
            {
              rejection_date: "",
              summa: "",
              org: "RET",
              claim_id: "300",
              rejection_reason: "",
              currency: "н\\д",
              branch: "20176",
              claim_date: "2022-04-07",
            },
            {
              rejection_date: "",
              summa: "",
              org: "RET",
              claim_id: "317",
              rejection_reason: "",
              currency: "н\\д",
              branch: "20176",
              claim_date: "2022-04-14",
            },
            {
              rejection_date: "",
              summa: "",
              org: "RET",
              claim_id: "348",
              rejection_reason: "",
              currency: "н\\д",
              branch: "20176",
              claim_date: "2022-04-19",
            },
            {
              rejection_date: "",
              summa: "",
              org: "RET",
              claim_id: "358",
              rejection_reason: "",
              currency: "н\\д",
              branch: "20176",
              claim_date: "2022-04-21",
            },
            {
              rejection_date: "",
              summa: "",
              org: "RET",
              claim_id: "88",
              rejection_reason: "",
              currency: "н\\д",
              branch: "20176",
              claim_date: "2022-02-05",
            },
            {
              rejection_date: "",
              summa: "",
              org: "RET",
              claim_id: "10098240740",
              rejection_reason: "",
              currency: "н\\д",
              branch: "20177",
              claim_date: "2021-11-19",
            },
          ],
        },
        contracts: {
          contract: [
            {
              contract_id: "36533",
              security_qty: "0",
              contract_status: "1",
              claim_id: "36533",
              branch: "01145",
              claim_id_change: "2022-01-18",
              percent: "34.9",
              amount_change: "2022-01-18",
              immediate_principal_sum_change: "2022-04-15",
              securities: null,
              contract_end_date: "2023-01-16",
              contract_date: "2022-01-17",
              class_asset_quality: "1",
              total_debt_sum: "973815105",
              contract_end_date_change: "2022-01-18",
              remaining_limit_sum: "0",
              currency: "000",
              immediate_principal_sum: "971029713",
              ID: "1",
              percent_change: "2022-01-18",
              amount_issued_change: "2022-04-15",
              amount: "1350000000",
              contract_date_change: "2022-01-18",
              org: "014",
              org_type: "БАНК",
              amount_issued: "1350000000",
              credit_type: "36",
              juridical_status: "08",
              total_debt_sum_change: "2022-04-15",
              claim_date: "2022-01-17",
              class_asset_quality_change: "2022-01-18",
              lawsuit_principal_sum: "",
              offbalance_princial_sum: "",
              actual_schedule: {
                actual_schedule_change: "2022-04-15",
                actual_repayment: [
                  {
                    principal_sum: "118400000",
                    repayment_date: "2022-02-02",
                    remaining_principal_sum: "1231600000",
                    percent_sum: "",
                  },
                  {
                    principal_sum: "150000000",
                    repayment_date: "2022-03-15",
                    remaining_principal_sum: "1081600000",
                    percent_sum: "",
                  },
                  {
                    principal_sum: "110570287",
                    repayment_date: "2022-04-15",
                    remaining_principal_sum: "971029713",
                    percent_sum: "",
                  },
                ],
              },
              forecasted_schedule: null,
              overdue_principals: null,
            },
            {
              contract_id: "297606",
              security_qty: "0",
              contract_status: "1",
              claim_id: "317049",
              branch: "01186",
              claim_id_change: "2021-07-19",
              percent: "0",
              amount_change: "2021-07-23",
              immediate_principal_sum_change: "2022-03-09",
              securities: null,
              contract_end_date: "2023-11-22",
              contract_date: "2020-01-23",
              class_asset_quality: "1",
              total_debt_sum: "149454213",
              contract_end_date_change: "2021-07-23",
              remaining_limit_sum: "0",
              currency: "000",
              immediate_principal_sum: "149454213",
              ID: "2",
              percent_change: "2021-07-23",
              amount_issued_change: "2022-03-09",
              amount: "1800000000",
              contract_date_change: "2021-07-23",
              org: "048",
              org_type: "БАНК",
              amount_issued: "1059768626",
              credit_type: "58",
              juridical_status: "08",
              total_debt_sum_change: "2022-03-09",
              claim_date: "2020-01-22",
              class_asset_quality_change: "2021-07-23",
              lawsuit_principal_sum: "",
              offbalance_princial_sum: "",
              actual_schedule: null,
              forecasted_schedule: {
                forecasted_schedule_change: "2021-07-23",
                forecasted_schedule_change_qty: 1,
                forecasted_payment: [
                  {
                    forecasted_payment_period: "2022-05",
                    principal_sum: "94736800",
                    percent_sum: "0",
                  },
                  {
                    forecasted_payment_period: "2022-06",
                    principal_sum: "94736800",
                    percent_sum: "0",
                  },
                  {
                    forecasted_payment_period: "2022-07",
                    principal_sum: "94736800",
                    percent_sum: "0",
                  },
                  {
                    forecasted_payment_period: "2022-08",
                    principal_sum: "94736800",
                    percent_sum: "0",
                  },
                  {
                    forecasted_payment_period: "2022-09",
                    principal_sum: "94736800",
                    percent_sum: "0",
                  },
                  {
                    forecasted_payment_period: "2022-10",
                    principal_sum: "94736800",
                    percent_sum: "0",
                  },
                  {
                    forecasted_payment_period: "2022-11",
                    principal_sum: "94736800",
                    percent_sum: "0",
                  },
                  {
                    forecasted_payment_period: "2022-12",
                    principal_sum: "94736800",
                    percent_sum: "0",
                  },
                  {
                    forecasted_payment_period: "2023-01",
                    principal_sum: "94736800",
                    percent_sum: "0",
                  },
                  {
                    forecasted_payment_period: "2023-02",
                    principal_sum: "94736800",
                    percent_sum: "0",
                  },
                  {
                    forecasted_payment_period: "2023-03",
                    principal_sum: "94736800",
                    percent_sum: "0",
                  },
                  {
                    forecasted_payment_period: "2023-04",
                    principal_sum: "94736800",
                    percent_sum: "0",
                  },
                  {
                    forecasted_payment_period: "2023-05",
                    principal_sum: "94736800",
                    percent_sum: "0",
                  },
                  {
                    forecasted_payment_period: "2023-06",
                    principal_sum: "94736800",
                    percent_sum: "0",
                  },
                  {
                    forecasted_payment_period: "2023-07",
                    principal_sum: "94736800",
                    percent_sum: "0",
                  },
                  {
                    forecasted_payment_period: "2023-08",
                    principal_sum: "94736800",
                    percent_sum: "0",
                  },
                  {
                    forecasted_payment_period: "2023-09",
                    principal_sum: "94736800",
                    percent_sum: "0",
                  },
                  {
                    forecasted_payment_period: "2023-10",
                    principal_sum: "94736800",
                    percent_sum: "0",
                  },
                  {
                    forecasted_payment_period: "2023-11",
                    principal_sum: "94737600",
                    percent_sum: "0",
                  },
                ],
              },
              overdue_principals: null,
            },
            {
              contract_id: "193955",
              security_qty: "0",
              contract_status: "2",
              claim_id: "202664",
              branch: "00996",
              claim_id_change: "2020-01-22",
              percent: "0",
              amount_change: "2020-01-23",
              immediate_principal_sum_change: null,
              securities: null,
              contract_end_date: "2023-11-22",
              contract_date: "2020-01-23",
              class_asset_quality: "1",
              total_debt_sum: null,
              contract_end_date_change: "2020-01-23",
              remaining_limit_sum: null,
              currency: "000",
              immediate_principal_sum: null,
              ID: "3",
              percent_change: "2020-01-23",
              amount_issued_change: "17-ИЮЛ-21",
              amount: "1800000000",
              contract_date_change: "2020-01-23",
              org: "048",
              org_type: "БАНК",
              amount_issued: "2360060237",
              credit_type: "58",
              juridical_status: "08",
              total_debt_sum_change: null,
              claim_date: "2020-01-22",
              class_asset_quality_change: "2020-01-23",
              lawsuit_principal_sum: null,
              offbalance_princial_sum: null,
              actual_schedule: null,
              forecasted_schedule: null,
              overdue_principals: null,
            },
          ],
        },
      },
    ];
    return {
      jsonDataArr,
    };
  },
};
</script>

<style></style>
